---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-gatekeeper-operator
spec:
  remediationAction: inform
  severity: high
  complianceType: musthave
  subscription:
    name: gatekeeper-operator-product
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  upgradeApproval: Automatic
---
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
    logLevel: INFO
    emitAuditEvents: Enabled
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    operations:
    - CREATE
    - UPDATE
    - DELETE
    replicas: 3
    logLevel: INFO
    emitAdmissionEvents: Enabled
    disabledBuiltins:
      - http.send 
