apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gatekeeper-operator-product.openshift-operators: ''
  name: gatekeeper-operator-product
  namespace: openshift-operators
spec:
  channel: '3.15'
  installPlanApproval: Automatic
  name: gatekeeper-operator-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gatekeeper-operator-product.v3.15.1
---
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
    logLevel: INFO
    emitAuditEvents: Enabled
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    operations:
    - CREATE
    - UPDATE
    replicas: 3
    logLevel: INFO
    emitAdmissionEvents: Enabled
    disabledBuiltins:
      - http.send 
