---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
spec:
  match:
    - excludedNamespaces:
        - ansible-automation-platform
        - hive
        - hypershift
        - policies
        - kube-*
        - local-quay
        - multicluster-engine
        - open-cluster-management
        - open-cluster-management-*
        - openshift-*
        - rhacs-operator
        - stackrox
      processes:
        - '*'

