apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: gatekeeper-placement
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
  
   
