apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    placementName: gatekeeper-placement
  remediationAction: enforce
  informGatekeeperPolicies: false 
  severity: medium
  ignorePending: true
policies:
  - name: setupgitops
    manifests:
      - path: setupgitops 
  - name: policy-install-gatekeeper
    manifests:
      - path: gatekeeperinstall
    remediationAction: enforce
  - name: policy-check-gatekeeper
    manifests:
      - path: gatekeeperchecks
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
    dependencies:
    - name: "policy-configure-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-applyconstraints
    manifests:
      - path: gatekeeperconstraint
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: gp-valid-apideprecation
    remediationAction: enforce
    manifests:
      - path: verify-deprecatedapi/constrainttemplate.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.16.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: verify-deprecatedapi/verifydeprecatedapi-1.22.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: verify-deprecatedapi/verifydeprecatedapi-1.25.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: verify-deprecatedapi/verifydeprecatedapi-1.26.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: verify-deprecatedapi/verifydeprecatedapi-1.27.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: verify-deprecatedapi/verifydeprecatedapi-1.29.yml
        extraDependencies: 
          - name: gp-valid-apidepreication
            kind: ConfigurationPolicy
            compliance: "Compliant"
   
   
