apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: gatekeeper-placement
  remediationAction: inform
  severity: medium
policies:
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
  - name: policy-installgatekeeper
    manifests:
      - path: gatekeeperinstall
  - name: policy-configure-gatekeeper
    manifests:
      - path: gatekeeperconfig
  - name: policy-check-gatekeeper
    manifests:
      - path: gatekeeperchecks
  - name: policy-applyconstraint
    manifests:
      - path: gatekeeperconstraint     
