apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: gatekeeper-placement
  remediationAction: enforce
  severity: medium
  ignorePending: true
policies:
  - name: policy-configure-gatekeeper
    manifests:
      - path: gatekeeperconfig
    remediationAction: enforce    
  - name: policy-check-gatekeeper
    manifests:
      - path: gatekeeperchecks
    dependencies:
    - name: "policy-configure-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"      
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
    dependencies:
    - name: "policy-configure-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-applyconstraints
    manifests:
      - path: gatekeeperconstraint
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
   
