apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: setupgitops
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: gatekeeper-placement
  remediationAction: inform
  severity: medium
policies:
  - name: setupgitops
    manifests:
      - path: gatekeeperlibrary
