apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    placementName: gatekeeper-placement
  remediationAction: enforce
  informGatekeeperPolicies: false 
  severity: medium
  ignorePending: true
policies:
  - name: policy-install-gatekeeper
    manifests:
      - path: gatekeeperinstall
    remediationAction: enforce
  - name: policy-check-gatekeeper
    manifests:
      - path: gatekeeperchecks
    remediationAction: inform
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-configure-gatekeeper
    manifests:
      - path: gatekeeperconfig
    remediationAction: enforce
    dependencies:
    - name: "policy-configure-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
    dependencies:
    - name: "policy-configure-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce 
  - name: policy-extraconstraints
    manifests:
      - path: extracontraints
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce
  - name: policy-applyconstraints
    manifests:
      - path: gatekeeperconstraint
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce
  - name: gp-valid-apideprecation
    remediationAction: enforce
    manifests:
      - path: verify-deprecatedapi/verifydeprecatedapi-1.16.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.22.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.25.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.26.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.27.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.29.yml
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
   
   
