apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gatekeeper
placementBindingDefaults:
  name: gatekeeper-placement-binding
policyDefaults:
  namespace: policies
  placement:
    placementName: gatekeeper-placement
  remediationAction: enforce
  policySets:
  - gatekeeper-policyset
  informGatekeeperPolicies: false 
  severity: medium
  ignorePending: true
policySetDefaults:
  # Optional. The placement configuration for the policy sets. This defaults to a placement configuration that matches
  # all clusters. If a placement.name is not provided here for placement consolidation, it will fall back to
  # policyDefaults.placement.name, if provided there. (See policyDefaults.placement for description.)
  placement: gatekeeper-placement
  # Optional. Whether to generate placement manifests for policy sets. This defaults to "true".
  generatePolicySetPlacement: true  
policies:
  - name: policy-install-gatekeeper
    manifests:
      - path: gatekeeperinstall
    remediationAction: enforce
  - name: policy-check-gatekeeper
    manifests:
      - path: gatekeeperchecks
    remediationAction: inform
    dependencies:
    - name: "policy-install-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-configure-gatekeeper
    manifests:
      - path: gatekeeperconfig
    remediationAction: enforce
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: policy-gatekeeperlibrary
    manifests:
      - path: gatekeeperlibrary
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce 
  - name: policy-extraconstraints
    manifests:
      - path: extracontrainttemplates
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce
  - name: policy-applyconstraints
    manifests:
      - path: gatekeeperconstraint
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
    remediationAction: enforce
  - name: gp-valid-apideprecation
    remediationAction: enforce
    manifests:
      - path: verify-deprecatedapi/verifydeprecatedapi-1.16.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.22.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.25.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.26.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.27.yml
      - path: verify-deprecatedapi/verifydeprecatedapi-1.29.yml
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
  - name: checkadmissionevents
    remediationAction: enforce
    manifests:
      - path: checkadmissionevents
    dependencies:
    - name: "policy-check-gatekeeper"
      compliance: "Compliant"
      kind: "Policy"
   
   
