apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: privilegedusers
spec:
  crd:
    spec:
      names:
        kind: RequiredGroups
      validation:
        legacySchema: true
        openAPIV3Schema:
          properties:
            groups:
              items: string
              type: array
            users:
              items: string
              type: array
  targets:
  - rego: "package privilegedusers\n\nuser_authorized(user, userlist) {\n   some i\n
      \  userlist[i] == user\n}\n\ngroup_authorized(group, grouplist) {\n   some i\n
      \  group[i] == grouplist[_]\n}\n\nviolation[{\"msg\": msg, \"details\": {}}]
      {\n   \n   operation := input.review.operation \n   operation == \"DELETE\"\n\n
      \  grouplist := input.parameters.groups\n   group := input.review.userInfo.groups\n
      \  not group_authorized(group, grouplist)\n\n   userlist := input.parameters.users
      \n   user := input.review.userInfo.username\n   not user_authorized(user, userlist)\n\n
      \  msg := sprintf(\"\\n\\nDENIED. Only the following users(%v) and members of
      groups(%v) can perform the action.\\n\", [userlist, grouplist])\n   }\n"
    target: admission.k8s.gatekeeper.sh
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredGroups
metadata:
  name: requiredgroups
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
    - apiGroups:
      - "project.openshift.io"
      kinds:
      - Project
  parameters:
    requiredGroups: ["developers"]
  enforcementAction: deny
