---
apiVersion: v1
kind: Pod
metadata:
  namespace: gatekeeper-system
  labels:
    control-plane: audit-controller
status:
  phase: Running   # check the pod status to determine if operator is running or not
---
apiVersion: v1
kind: Pod
metadata:
  namespace: gatekeeper-system
  labels:
    control-plane: controller-manager
status:
  phase: Running  
