apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: demo-annotation-owner
spec:
  match:
    scope: Namespaced
    name: "book*"
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaces: ["remote"]
  location: "metadata.annotations.owner"
  parameters:
    assign:
      value:  "admin"



