apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenySecretDeleteIfUsedByVM
metadata:
  name: deny-secret-delete-if-used-by-vm
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Secret"]
