apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: networkpolicydenyfromdefault
spec:
  crd:
    spec:
      names:
        kind: NetworkPolicy
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8s.networkpolicies
        deny_ingress_from_default_ns {
            input.policy.spec.ingress[_].from[_].namespace == "default"
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NetworkPolicy
metadata:
  name: deny-ingress-from-default
spec:
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["NetworkPolicy"]
  parameters:
    severity: "high"
