---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoAppInDefaultArgoProject
metadata:
  name: no-app-in-default-argo-project
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["argoproj.io/v1alpha1"]
        kinds: ["Application"]
