---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ValidateUserInfo
metadata:
  name: validatevm
spec:
  match:
    kinds:
      - apiGroups: ["kubevirt.io"]
        kinds: ["VirtualMachine"]
  parameters:
    requiredGroupDev: ["dev-group"]
    requiredGroupProd: ["prod-group"]
