---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyClusterDeploymentDelete 
metadata:
  name: denyclusterdeploymentdelete
spec:
  enforcementAction: dryrun
  parameters:
    clusterRole: "superadmin"
    denyDelete: true
