---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: denyclusterdeploymentdelete 
metadata:
  name: denyclusterdeploymentdel
spec:
  enforcementAction: dryrun
  parameters:
    clusterRole: "superadmin"
    denyDelete: true
